# Prompt format
format = "$directory$git_branch$git_state$git_status$line_break$character"

# Set command_timeout directly
command_timeout = 1000

# Set add_newline directly
add_newline = false

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[hostname]
disabled = true

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "($ahead_behind$stashed)($style)"
style = "cyan"
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "≡"
