require('configs.lsp_config')
require('configs.cmp-config')
require('configs.nvim-tree')
require('configs.treesitter')
require('configs.nvim-autopairs')
require('configs.luasnip')
require('configs.css-colors')
